<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
<?php echo $this->headMeta()->setIndent(2) . "\n"; ?>
<?php $this->headTitle(\Zend_Registry::get('siteName'), \Zend_View_Helper_Placeholder_Container_Abstract::SET)->setSeparator(' :: ')->setIndent(2); ?>
<?php echo $this->headTitle(html_entity_decode(strip_tags($this->pageTitle()), ENT_QUOTES, 'UTF-8')) . "\n"; ?>
<?php $this->jquery(); ?>
<?php echo $this->headLink()->appendStylesheet('/css/zyndax.YYYYMMDD.css', 'all')->setIndent(2) . "\n"; ?>
<?php echo $this->headScript()->setIndent(2) . "\n"; ?>
<!--[if (gte IE 6) &(lte IE 8)]>
  <script type="text/javascript" src="/js/libs/selectivizr.min.js"></script>
<![endif]-->
</head>
<body class="<?php echo $this->bodyClass(); ?>">
 <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6. chromium.org/developers/how-tos/chrome-frame-getting-started -->
 <!--[if lt IE 7]><p class="chromeframe">Your browser does not adhere to web standards. For a better experience, please <a href="http://browsehappy.com/">upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install the Google Chrome Frame</a> add-on.</p><![endif]-->

  <header>
    <div class="global-nav">
      <?php echo $this->navbar() ?>
    </div>
  </header>

  <div id="main" role="main">
    <div id="precontent">
      <h1><?php echo $this->pageTitle() ?></h1>
      <?php echo $this->contextualLinks() ?>
    </div>
    <div id="content" class="clearfix">
      <?php echo $this->messages()->render(); ?>
      <?php echo $this->layout()->content; ?>
    </div>
  </div>

  <footer>
    <p class="copyright">Copyright &copy; 2011<?php $y = date('Y'); if($y > 2011) { echo '&ndash;'.$y; } ?> <a href="http://example.com/">Example, LLC</a>. All rights reserved. <a href="http://example.com/privacy.html">Privacy Policy</a></p>
    <p class="zyndax-version">Zyndax v<?php echo Zend_Registry::get('version') ?> build <?php echo Zend_Registry::get('build') ?></p>
  </footer>

<?php echo $this->inlineScript() . "\n"; ?>
<?php echo $this->jquery() . "\n"; ?>

</body>
</html>
