<?php echo $this->form ?>

<div class="autoscroll">
  <table class="list">
    <thead><tr>
  <?php echo $this->jquery()->tableHeader('name') ?>
  <?php echo $this->jquery()->tableHeader('description') ?>
  <th class="action"></th>
    </tr></thead>
    <tbody>
    <?php foreach($this->groups as $group): ?>
  <tr id="group-<?php echo $group->getId().($group->getLocked() ? '" class="locked"' : '') ?>">
    <td><?php echo '<a href="'.$this->baseUrl().'/groups/edit/'.$group->getId().'">'.$this->escape($group->getName()).'</a>'; ?></td>
    <td><?php echo $this->escape($group->getDescription()) ?></td>
    <td class="smaller"><?php echo $this->groupLockLink($group); ?></td>
  </tr>
    <?php endforeach ?>
    </tbody>
    <tfoot>
  <tr><th colspan="3"><?php echo $this->paginationLinks ?></th></tr>
    </tfoot>
  </table>
</div>
