<?php if($this->message === 404): ?>
  <p>Looks like you stumbled across a page that does not exist.</p>
  <p>Perhaps you would like to go to the <a href="<?php echo $this->url(array(), 'home') ?>" title="Go home">home page</a>?</p>
<?php else: ?>
  <h2><?php echo $this->message ?></h2>
  <?php if(isset($this->exception)): ?>
  <h3>Exception information:</h3>
  <p>
    <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?></pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
  <?php endif ?>
<?php endif ?>
